# Base config file for all sim envs. Other envs will use these values unless they are specifically overwritten
# with their own config files.

# note: as a rule of thumb, these values should be as reusable as possible between envs, while values that
#       are expected to change between each env should be actual class parameters.

# resetting
reset_base_tool_tf: [-0.226, .849, 1.071, .008, .006, .632]  # 3 for trans, 3 for rot as explained in README
reset_joint_pos: [-1.38, -1.51, -1.88, -.38, 1.13, 2.89]     # 1 per joint, ensures consistent pose for above tf

# control
control_type: 'delta_tool'    # 'delta_tool', 'delta_joint', 'pos_tool', 'pos_joint', 'vel_tool', 'vel_joint'
rot_act_rep: 'rod'            # 'rod' for rodrigues, 'quat' for quaternion
control_freq: 8               # in Hz
poses_ref_frame: 'b'          # 'b' or 'w' for base or world
arm_max_trans_vel: .15        # m/s, also value used for resets
arm_max_rot_vel: .3           # rad/s, also used for resets
max_policy_time: .07          # max expected time that a running policy would take -- this should be set as low as possible
                              # this also should include the max time to process images before they are returned
                              # in step

# physical constraints
pos_limits: [-1., -1., -1., 1., 1., 1.]   # corners of a box relative to the robot base origin

# images
img_width: 64
img_height: 48
img_zoom_crop: 2.0        # e.g. 2.0 cuts out half of height, half of width, only taking middle
alt_img_topic: null         # if different from default from kinect or sim kinect
alt_depth_topic: null       # if different from default from kinect or sim kinect

# base params (if moving_base is true -- otherwise ignored)
base_theta_maximums: [-.4, .4]    # radians based on making a circle around the workspace center
cam_workspace_distance: .8        # meters from cam frame to workspace center
base_reset_noise: .02             # std in meters and radians for resets of base

# other data
additional_topics: []       # other topics to add to state